Repository soolsul/soolsul-client, pull requests merged in 2022-11, with the labels that each got.

#3 [Setting] Property 세팅 수정 #1
  src/lib/utils/Properties.ts
  src/pages/index.tsx
Labels: feat, setting

#7 [Feat]: 지도 화면 구현 #5
  package.json
  src/components/Input/TextInput.tsx
  src/components/Input/index.ts
  src/components/Loader/Spinner.tsx
  src/components/Loader/index.ts
  src/components/pages/map/AddFeedButton.tsx
  src/components/pages/map/BottomMenu.tsx
  src/components/pages/map/Category.tsx
  src/components/pages/map/Error.tsx
  src/components/pages/map/SearchBar.tsx
  src/components/pages/map/index.ts
  src/hooks/pages/login/index.ts
  src/hooks/pages/login/useLogin.tsx
  src/hooks/pages/map/useBottomMenu.tsx
  src/lib/types/user.ts
  src/lib/utils/Properties.ts
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/map/index.tsx
  tsconfig.json
  yarn.lock
Labels: feat

#8 [Feat] watchPositon 사용 및 eslint 오류 수정
  .eslintrc.json
  package-lock.json
  src/apis/users.tsx
  src/components/pages/map/Error.tsx
  src/hooks/pages/map/useBottomMenu.tsx
  src/lib/utils/Properties.ts
  src/pages/index.tsx
  src/pages/map/index.tsx
  yarn.lock
Labels: bug, feat

#10 [Feat] 마이페이지 내 댓글, 관심목록 UI구현 #6
  src/components/pages/profile/mainSection/MainSection.tsx
  src/components/pages/profile/mainSection/MyFavorite.tsx
  src/components/pages/profile/mainSection/MyReply.tsx
Labels: feat

#11 [Feat] 마이페이지 프로필 편집 UI 구현 #6
  src/components/pages/map/Category.tsx
  src/components/pages/profile/UserInfo.tsx
  src/components/pages/profile/mainSection/Empty.tsx
  src/components/pages/profile/mainSection/Header.tsx
  src/components/pages/profile/mainSection/MainSection.tsx
  src/components/pages/profile/mainSection/MyFavorite.tsx
  src/components/pages/profile/mainSection/MyPost.tsx
  src/components/pages/profile/mainSection/MyReply.tsx
  src/pages/mypage/[category]/index.tsx
  src/pages/mypage/edit.tsx
Labels: feat

#13 [Feat] PWA 적용 #12
  next.config.js
  package.json
  public/favicon.ico
  public/images/favicons/favicon-16x16.png
  public/images/favicons/favicon-32x32.png
  public/images/icons/icon-128x128.png
  public/images/icons/icon-144x144.png
  public/images/icons/icon-152x152.png
  public/images/icons/icon-192x192.png
  public/images/icons/icon-384x384.png
  public/images/icons/icon-48x48.png
  public/images/icons/icon-512x512.png
  public/images/icons/icon-72x72.png
  public/images/icons/icon-96x96.png
  public/manifest.json
  public/sw.js
  public/sw.js.map
  public/workbox-327c579b.js
  public/workbox-327c579b.js.map
  src/pages/_document.tsx
  yarn.lock
Labels: feat

#20 [Feat] Feed 페이지 UI 구현 #14
  src/components/common/ProfileImage.tsx
  src/components/common/commonStyle.tsx
  src/components/pages/feed/Post.tsx
  src/components/pages/feed/PostItem.tsx
  src/components/pages/feed/index.ts
  src/components/pages/map/Category.tsx
  src/components/pages/map/SearchBar.tsx
  src/components/pages/profile/Header.tsx
  src/components/pages/profile/UserInfo.tsx
  src/components/pages/profile/mainSection/MyFavorite.tsx
  src/components/pages/profile/mainSection/MyReply.tsx
  src/pages/feed/index.tsx
  src/pages/mypage/edit.tsx
  src/styles/globals.css
Labels: feat

#24 [Feat]: barList 조회 기능 구현
  src/apis/bar.ts
  src/apis/index.ts
  src/apis/network.ts
  src/lib/types/bar.ts
  src/lib/types/index.ts
  src/pages/map/index.tsx
Labels: feat

#29 [Feat]: 회원가입 및 로그인 기능 구현
  src/apis/network.ts
  src/apis/users.tsx
  src/components/pages/login/LoginInput.tsx
  src/hooks/pages/login/useLogin.tsx
  src/hooks/pages/signup/useSignup.ts
  src/lib/types/user.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: feat

#33 [Feat]: 큐레이션 UI 구현
  src/assets/images/curation/clock.svg
  src/assets/images/curation/map.svg
  src/assets/images/curation/phone.svg
  src/assets/images/curation/r_menu.svg
  src/assets/images/curation/storeIcon.png
  src/components/common/Line.tsx
  src/components/pages/curation/CurationDetailContents.tsx
  src/components/pages/curation/CurationItem.tsx
  src/components/pages/curation/Info.tsx
  src/components/pages/curation/InfoSection.tsx
  src/components/pages/curation/Review.tsx
  src/components/pages/curation/SelectHeader.tsx
  src/components/pages/curation/TagItem.tsx
  src/components/pages/curation/index.ts
  src/pages/curation/detail.tsx
  src/pages/curation/index.tsx
  tsconfig.path.json
Labels: fix

#34 [Feat]: 큐레이션 메인 및 상세 페이지 UI 구현
  src/assets/images/curation/heart.svg
  src/components/pages/curation/CurationDetailContents.tsx
  src/components/pages/curation/CurationItem.tsx
  src/components/pages/curation/InfoSection.tsx
  src/components/pages/curation/Review.tsx
  src/components/pages/curation/ReviewItem.tsx
  src/components/pages/curation/SelectHeader.tsx
  src/pages/curation/detail/[category]/index.tsx
  src/pages/curation/index.tsx
Labels: feat
